version: '3.1'

services:
  tepb-db:
    image: mysql
    restart: always
    container_name: dev-tepb-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "dev_tepb_db"
      MYSQL_ROOT_PASSWORD: "dev_tepb_db_root_password"