version: '3.1'

services:
  tepb-bot:
    depends_on:
      - tepb-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  tepb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'tepb_db'
      MYSQL_ROOT_PASSWORD: 'tepb_db_root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'