version: '3.9'

services:
  telegram-event-planner-bot:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/tepb?ApplicationName=telegram-event-planner-bot
      SPRING_DATASOURCE_USERNAME: ${BOT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${BOT_DB_PASSWORD}
      SPRING_BOT_NAME: ${BOT_NAME}
      SPRING_BOT_TOKEN: ${BOT_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure